---
title: "Sandbox Analysis"
format: html
editor: visual
---

## lhprism_data sandbox analysis

this document is the playground for seeing how to sort the lhprism_data dataset in effort to examine how long it takes to go from initial treatment of an invasive species on a site location until it's eradication.

```{r}
## Get packages
library(pacman)
pacman::p_load(here, tidyverse, janitor, lubridate)

## Get the project level directory path
proj_path <- here()

## Define a color blind friendly palette
## These are from - http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/
# The palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r}
## Read in the data file
lhprism_data <- read_csv(paste0(proj_path, "/data/LHPRISM-Data.csv"), 
    col_types = cols(`iMap Treat` = col_number(), 
        GROSS_TREAT_SQFT = col_number())) %>%
  clean_names()

## Edit the order of levels for some of the variables
lhprism_data <- lhprism_data %>%
  mutate(native = factor(native, levels = c("low", "medium", "high")),
         non_nat = factor(non_nat, levels = c("low", "medium", "high")))

## Create a new species code column
lhprism_data$species_code <- str_extract(lhprism_data$site_code, "(?<=_)[^_]+(?=_)") 
## Remove plant column
lhprism_data$plant <- NULL

## Create a new site column using the species_code column
lhprism_data$site <- str_extract(lhprism_data$site_code, "^[^_]+")

## Remove all rows that have NA for site
lhprism_data <- lhprism_data %>%
  filter(!is.na(site))
```

```{r}
library(dplyr)

lhprism_data <- lhprism_data %>%
  count('site')
```
